"""add achievement city_visit tables

Revision ID: 63f9df5ac45d
Revises: fe56fa70289e
Create Date: 2026-03-17 09:54:15.380938

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '63f9df5ac45d'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('category', sa.Enum('EXPLORER', 'REGIONAL', 'FOODIE', 'SOCIAL', 'COMPANION', name='achievementcategory'), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'RARE', 'EPIC', 'LEGENDARY', name='achievementrarity'), nullable=False),
    sa.Column('icon_url', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('condition_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reward_mood', sa.Integer(), nullable=False),
    sa.Column('reward_energy', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_code'), 'achievements', ['code'], unique=True)
    op.create_table('city_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('city_name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('province', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('visited_at', sa.DateTime(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_city_visits_city_name'), 'city_visits', ['city_name'], unique=False)
    op.create_index(op.f('ix_city_visits_user_id'), 'city_visits', ['user_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_city_visits_user_id'), table_name='city_visits')
    op.drop_index(op.f('ix_city_visits_city_name'), table_name='city_visits')
    op.drop_table('city_visits')
    op.drop_index(op.f('ix_achievements_code'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
